name: Bazel Targets Scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detect-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install bazel-diff
        run: |
          curl -Lo bazel-diff.jar https://github.com/Tinder/bazel-diff/releases/latest/download/bazel-diff_deploy.jar
          java -jar bazel-diff.jar -h
      
      - name: Bazel-diff Generate Hashes
        run: |
          java -jar bazel-diff.jar  generate-hashes --workspacePath $GITHUB_WORKSPACE --bazelPath $(which bazel) ending-hash.json

      # - name: Endor Scan Targets
      #   if: steps.set-targets.outputs.targets != ''
      #   uses: endorlabs/github-action@main
      #   with: 
      #     namespace: 'kriti-learn'
      #     scan_dependencies: true
      #     pr: false
      #     scan_summary_output_type: 'table'
      #     additional_args: "--bazel-include-targets=${{ steps.set-targets.outputs.targets }}"
